#pragma once

#include <cstdint>

#include "lib/utils/enum.h"

MAKE_ENUM(PacketType, uint8_t,
    POWER, 0x01,

    NIGHT_MODE_ENABLED, 0x20,
    NIGHT_MODE_START, 0x21,
    NIGHT_MODE_END, 0x22,

    SYS_CONFIG_MDNS_NAME, 0x60,

    SYS_CONFIG_WIFI_MODE, 0x61,
    SYS_CONFIG_WIFI_SSID, 0x62,
    SYS_CONFIG_WIFI_PASSWORD, 0x63,
    SYS_CONFIG_WIFI_CONNECTION_CHECK_INTERVAL, 0x64,
    SYS_CONFIG_WIFI_MAX_CONNECTION_ATTEMPT_INTERVAL, 0x65,

    SYS_CONFIG_STEPPER_1_PIN, 0x66,
    SYS_CONFIG_STEPPER_2_PIN, 0x67,
    SYS_CONFIG_STEPPER_3_PIN, 0x68,
    SYS_CONFIG_STEPPER_4_PIN, 0x69,
    SYS_CONFIG_STEPPER_EN_PIN, 0x6A,

    SYS_CONFIG_TIME_ZONE, 0x6C,

    SYS_CONFIG_MQTT_ENABLED, 0x70,
    SYS_CONFIG_MQTT_HOST, 0x71,
    SYS_CONFIG_MQTT_PORT, 0x72,
    SYS_CONFIG_MQTT_USER, 0x73,
    SYS_CONFIG_MQTT_PASSWORD, 0x74,
    SYS_CONFIG_MQTT_CONVERT_BRIGHTNESS, 0x75,

    SYS_CONFIG_ENDSTOP_PIN, 0x81,
    SYS_CONFIG_ENDSTOP_HIGH_STATE, 0x82,

    GET_CONFIG, 0xa0,
    RESTART, 0xb0,
)
